plugins:
  - jekyll-paginate

title: BlogSatu
description: BlogSatu adalah blog tentang internet banking, tutorial windows, aplikasi komputer, pemrograman
katakunci: windows tutorial, tutorial aplikasi, tutorial youtube, hp, iphone, android, jaringan, internet banking, internet
pertamaterbit: 2022-03-29
terakhirupdate: 2022-04-01

paginate: 10
paginate_path: /page/:num/
permalink: /:slug

# url
category_dir: category/
tag_dir: tag/

url: "https://blogsatu.net"

excerpt_separator: "\n\n\n\n"